SP=/afs/cs.wisc.edu/p/paradyn/development/wenbin/spi
BIN=/scratch/wenbin/binaries/bin/bin
TRG=../target/$PLATFORM

#source ../make.config
AGENT_NAME=libmyagent.so
export LD_LIBRARY_PATH=$SP_DIR/$PLATFORM:$LD_LIBRARY_PATH

#export SP_DEBUG=0
CWD=`pwd`

cd $TRG
#LD_PRELOAD="$CWD/$AGENT_NAME" ./test$1 1 2 3 #> /dev/null
LD_PRELOAD="$CWD/$AGENT_NAME" ./demo 1 2 3 > /dev/null

#echo 1; LD_PRELOAD="./$AGENT_NAME" $BIN/[
#echo 2; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/base64 /tmp/tmp > /dev/null
#echo 3; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/basename /tmp/tmp > /dev/null
#echo 4; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/cat /tmp/tmp > /dev/null
#echo 5; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/chmod 757 /tmp/tmp > /dev/null
#echo 6; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/head /tmp/tmp > /dev/null
#echo 7; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/mv /tmp/tmp /tmp/tmp1 > /dev/null
#echo 8; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/cp -f /tmp/tmp1 /tmp/tmp > /dev/null
#echo 9; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/rm /tmp/tmp1 > /dev/null
#echo 10; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/uname -a > /dev/null
#echo 11; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/df > /dev/null
#echo 12; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/hostid > /dev/null
#echo 13; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/nice > /dev/null
#echo 14; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/rmdir /tmp/a > /dev/null
#echo 15; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/stty > /dev/null
#echo 16; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/unexpand /tmp/tm > /dev/nullp
#echo 17; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/dir > /dev/null
#echo 18; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/id > /dev/null
#echo 19; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/nl /tmp/tmp > /dev/null
#echo 20; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sum /tmp/tmp > /dev/null
#echo 21; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/uniq /tmp/tmp > /dev/null
#echo 22; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/dircolors > /dev/null
#echo 23; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/install /tmp/tmp /tmp/tmp1 > /dev/null
#echo 24; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/seq 1 2 3 > /dev/null
#echo 25; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/unlink /tmp/tmp1 > /dev/null
#echo 26; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/dirname /tmp/tmp1 > /dev/null
#echo 27; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/tac /tmp/tmp > /dev/null
#echo 28; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/uptime > /dev/null
#echo 29; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sha1sum /tmp/tmp > /dev/null
#echo 30; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/du > /dev/null
#echo 31; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/tail /tmp/tmp > /dev/null
#echo 32; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/users > /dev/null
#echo 33; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sha224sum /tmp/tmp > /dev/null
#echo 34; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/echo /tmp/tmp > /dev/null
#echo 35; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/link /tmp/tmp /tmp/tmp3 > /dev/null
#echo 36; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sha256sum /tmp/tmp > /dev/null
#echo 37; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/tee > /dev/null
#echo 38; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/vdir > /dev/null
#echo 39; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/wc -c /tmp/tmp > /dev/null
#echo 40; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/chown wenbin /tmp/tmp > /dev/null
#echo 41; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/env > /dev/null
#echo 42; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/ln /tmp/tmp /tmp/tmp5 > /dev/null
#echo 43; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/ln /tmp/tmp /tmp/tmp5 > /dev/null
#echo 44; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/pathchk /tmp/tmp > /dev/null
#echo 45; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/test > /dev/null
#echo 46; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sha384sum /tmp/tmp > /dev/null
#echo 47; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/date > /dev/null
#echo 48; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/expand /tmp/tmp > /dev/null
#echo 49; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/logname > /dev/null
#echo 50; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/pinky > /dev/null
#echo 51; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sha512sum /tmp/tmp > /dev/null
#echo 52; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/who > /dev/null
#echo 53; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/cksum /tmp/tmp > /dev/null
#echo 54; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/whoami > /dev/null
#echo 55; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/ls > /dev/null
#echo 56; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/ls $1 > /dev/null
#echo 57; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/true > /dev/null
#echo 58; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/false > /dev/null
#echo 59; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sleep 2 > /dev/null
#echo 60; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/sort /tmp/tmp > /dev/null
#echo 61; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/tsort /tmp/tmp > /dev/null
#echo 62; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/pwd > /dev/null
#echo 63; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/md5sum /tmp/tmp > /dev/null
#echo 64; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/ptx /tmp/tmp > /dev/null
#echo 65; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/stat /tmp/tmp > /dev/null
#echo 66; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/yes > /dev/null
#echo 67; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/factor 10286 > /dev/null
#echo 68; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/printenv > /dev/null
#echo 69; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/printenv > /dev/null
#echo 70; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/readlink /tmp/tmp > /dev/null
#echo 71; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/mktemp > /dev/null
#echo 72; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/groups > /dev/null
#echo 73; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/mkdir -p /tmp/tmp99/tmp3 > /dev/null
#echo 74; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/printf "abasdfaf%s" "aaa" > /dev/null
#echo 75; LD_PRELOAD="$CWD/$AGENT_NAME" $BIN/od /tmp/tmp > /dev/null

#time LD_PRELOAD="$CWD/$AGENT_NAME" /scratch/wenbin/software/libexec/gcc/x86_64-unknown-linux-gnu/4.5.2/cc1 200.i
