IJ_SRCS       =  ../src/Injector/SpInjector-x86_64.C \

AG_SRCS       =  ../src/Agent/SpEvent-x86_64.C \


PLATFORM      ?= x86_64-unknown-linux2.4

include ../make.config
include ../make.flag.tmpl
include ../make.module.tmpl
