IJ_SRCS       =  ../src/injector/injector-x86_64.cc \

AG_SRCS       =  ../src/agent/snippet-x86_64.cc \

UTILS_SRCS    = 

PLATFORM      ?= x86_64-unknown-linux2.4

include ../make.config
include ../make.flag.tmpl
include ../make.module.tmpl
