IJ_SRCS       =  ../src/injector/injector-x86_64.cc \

AG_SRCS       =  ../src/agent/snippet-x86_64.cc \
                 ../src/agent/patchapi/addr_space-x86_64.cc \
                 ../src/agent/patchapi/object-x86_64.cc \

UTILS_SRCS    = 

PLATFORM      ?= x86_64-unknown-linux2.4

include ../config.mk
include ../common.flag.mk
include ../spi.target.mk
