/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.14";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/afs/cs.wisc.edu/p/paradyn/development/wenbin/spi/spi/i386-unknown-linux2.4/tmp/etc/wgetrc\" -DLOCALEDIR=\"/afs/cs.wisc.edu/p/paradyn/development/wenbin/spi/spi/i386-unknown-linux2.4/tmp/share/locale\" -I. -I../lib -I../lib -O2 -Wall";
const char *link_string = "gcc -O2 -Wall -lz -lidn -luuid -lpcre -lrt ftp-opie.o ../lib/libgnu.a";
