IJ_SRCS       =  ../src/injector/injector-i386.cc \

AG_SRCS       = ../src/agent/snippet-i386.cc \
                ../src/agent/parser-i386.cc \
                ../src/agent/patchapi/object-i386.cc \

UTILS_SRCS    = 

PLATFORM      ?= i386-unknown-linux2.4

include ../config.mk
include ../common.flag.mk
include ../spi.target.mk
