IJ_SRCS       =  ../src/Injector/SpInjector-i386.C \

AG_SRCS       = ../src/Agent/SpArch-i386.C \

SERVER_SRCS   =

PLATFORM      ?= i386-unknown-linux2.4

include ../make.config
include ../make.flag.tmpl
include ../make.module.tmpl
