IJ_SRCS       =  ../src/injector/injector-i386.cc \

AG_SRCS       = ../src/agent/snippet-i386.cc \

UTILS_SRCS    = 

PLATFORM      ?= i386-unknown-linux2.4

include ../make.config
include ../make.flag.tmpl
include ../make.module.tmpl
